package entity;
// Generated Sep 22, 2019 8:37:37 PM by Hibernate Tools 4.3.1



/**
 * ProOrderDetailes generated by hbm2java
 */
public class ProOrderDetailes  implements java.io.Serializable {


     private Integer orderDatiles;
     private ProOrder proOrder;
     private Product product;
     private int proQty;

    public ProOrderDetailes() {
    }

    public ProOrderDetailes(ProOrder proOrder, Product product, int proQty) {
       this.proOrder = proOrder;
       this.product = product;
       this.proQty = proQty;
    }
   
    public Integer getOrderDatiles() {
        return this.orderDatiles;
    }
    
    public void setOrderDatiles(Integer orderDatiles) {
        this.orderDatiles = orderDatiles;
    }
    public ProOrder getProOrder() {
        return this.proOrder;
    }
    
    public void setProOrder(ProOrder proOrder) {
        this.proOrder = proOrder;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public int getProQty() {
        return this.proQty;
    }
    
    public void setProQty(int proQty) {
        this.proQty = proQty;
    }




}


